name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
defaults:
  run:
    working-directory: ./code

jobs:
  Unit-Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Debug repository structure
      run: ls -R /home/runner/work/trojan1-eventbuddy/trojan1-eventbuddy 
    - name: Create necessary directories
      run: mkdir -p /home/runner/work/trojan1-eventbuddy/trojan1-eventbuddy/code/app
    - name: Create Google Services JSON File
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON | base64 -di > /home/runner/work/trojan1-eventbuddy/trojan1-eventbuddy/code/app/src/google-services.json
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Unit Tests
      run: ./gradlew test

  UI-Tests:
    runs-on: [ macos-12 ]
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > /home/runner/work/trojan1-eventbuddy/trojan1-eventbuddy/code/app/google-services.json
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: cd ./code && ./gradlew connectedDebugAndroidTest
